### ISSUE TITLE
When will you release the inference code and weight for the ACInterp module ？

### ISSUE THREAD

**Issue by haoxurt** [CyberAgentAILab/TANGO#7]
When will you release the inference code and weight for the ACInterp module ？

**Comment by H-Liu1997** [comment]
I'm working on my PhD thesis recently so it'll be clean up around the end of this year.

**Comment by H-Liu1997** [comment]
@XingWang1234 thank you for your positive feedback! 
yes, the demo use FiLM (an open-source, non-diffusion based model) to generate transition frames, instead of ACInterp.  With ACInterp the finger or hands disapear issue, in the transition part will be better. 

if in your results there is no hands or body-part disapper issue in your test data, may be add ACInterp will no further benefits

**Comment by XingWang1234** [comment]
@H-Liu1997 Thank you so much for the clarification.
